baseURL = "https://www.avvocatomaenza.it/"
languageCode = "it-it"
title = "Avvocato Massimiliano Maenza"
theme = "PaperMod"
publishDir = "public"

[params]
  defaultTheme = "auto"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true